trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
jsxSingleQuote: false
arrowParens: avoid
bracketSpacing: true
endOfLine: "lf"
printWidth: 80
plugins:
  - prettier-plugin-astro

overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
